<a href="https://colab.research.google.com/github/n0ximus/TensorFlowPractice/blob/main/00_TF_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Most fundamental concepts of tensors in TF.
- intro to tensors
- getting info from tensors
- manipulating tensors
- tensors and numpy
- using @tf.function (speeds up regular python functions)
- using gpus/tpus with TF

# intro to tensors

In [ ]:
#import TF
import tensorflow as tf 
print(tf.__version__)

2.8.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check number of dimensions of a tensor (ndim - number of dimensions)
scalar.ndim

0

In [ ]:
# create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# vector dimension
vector.ndim

1

In [ ]:
# create matrix 
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# create other matrix 
another = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16) # specify data type with dtype param
another


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# dimentions of another
another.ndim

2

In [ ]:
# creating a tensor
tensor = tf.constant([[[1,2,3,],[4,5,6]], [[7,8,9,], [10,11,12]], [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Scalar- single number
Vector- number with direction 
Matrix- 2d array of numbers
Tensor- n-dimensional array of numbers (where n is any number)
n=0 -> scalar
n=1 -> vector
n=2 -> matrix

In [ ]:
# tensors with tf.Variable
changeableTensor = tf.Variable([10,7])
unchangeableTensor = tf.constant([10,7])
changeableTensor, unchangeableTensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# let's try change one of the elements
changeableTensor[0] = 7
changeableTensor

TypeError: ignored

In [ ]:
# let's try change one of the elements
changeableTensor[0].assign(7)
changeableTensor

# creating random tensors 
random tensors are tensors of some arbitrary size which contain random numbers
- output starts with random tensors and the algorithm alters these valuees to produce the appropriate output

In [ ]:
# create two random (but the same) tensors
random1 = tf.random.Generator.from_seed(42) # set seed for reproducibility 
random1 = random1.normal(shape=(3,2))
random2 = tf.random.Generator.from_seed(42)
random2 = random2.normal(shape=(3,2))

random1, random2, random1 == random2



shuffle order of elements in tensor

In [ ]:
# shuffle tensor (valuable when you want to suffle data so inherent order does not affect learning)
shuffle = tf.constant([[10,7], [3,4], [2,5]])
tf.random.shuffle(shuffle)


In [ ]:
# shuffle tensor (valuable when you want to suffle data so inherent order does not affect learning)
shuffle = tf.constant([[10,7], [3,4], [2,5]])
tf.random.set_seed(42) # global level seed 
tf.random.shuffle(shuffle, seed=42) # operation level seed

In [ ]:
# create tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensor of all zeroes
tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

## turn numpy arrays into tensors 
- main difference between numpy and tensors is that tensors can be run on GPU


In [ ]:
# you can also turn numpy arrays into tensor
import numpy as np
numpyA = np.arange(1, 25, dtype=np.int32) # create numpy array between 1 and 25
numpyA

In [ ]:
A = tf.constant(numpyA, shape=(2,3,4))
B = tf.constant(numpyA)

A, B

In [ ]:
A.ndim

# getting info from tensors
When dealing with tensors, know the following attributes
- shape = length (# of elements) of each of the dimensions of a tensor (tensor.shape)
- rank = number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n (tensor.ndim)
- axis or dimension = particular dimensions of a tensor (tensor[0], tensor[:,1]...)
- size = total number of itmes in the tensor (tf.size(tensor))

In [ ]:
# create a rank 4 tensor (4d)
rank4Tensor = tf.zeros(shape=[2,3,4,5])
rank4Tensor

In [ ]:
rank4Tensor[0]

In [ ]:
rank4Tensor.shape, rank4Tensor.ndim, tf.size(rank4Tensor)

In [ ]:
# get various attributes of tensor 
print("Datatype of every element: ", rank4Tensor.dtype)
print("number of dimensions: ", rank4Tensor.ndim)
print("shape of tensor: ", rank4Tensor.shape)
print("Elements along the 0 axis: ", rank4Tensor.shape[0])
print("Elements along the last axis: ", rank4Tensor.shape[-1])
print("total number of elements in our tensor: ", tf.size(rank4Tensor).numpy())

# indexing tensors 
- tensors can be indexed just like python lists 

In [ ]:
# get the first 2 elements of each dimension
rank4Tensor[:2,:2,:2,:2]


In [ ]:
# get first element from from each dimension from each index except for the final one
rank4Tensor[:1,:1,:,:1]

In [ ]:
# rank 2 tensor (2d)
rank2Tensor = tf.constant([[10,7], [3,4]])
rank2Tensor.shape, rank2Tensor.ndim

In [ ]:
# get the last item of each of our rank 2 tensor
rank2Tensor[:,-1]

In [ ]:
# add extra dimension
rank3 = rank2Tensor[:, :, tf.newaxis]
# same thing as below vvvvvvvvvv
rank3 = rank2Tensor[..., tf.newaxis]
rank3

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank2Tensor, axis=-1) # "-1" means expand the final axis

In [ ]:
tf.expand_dims(rank2Tensor, axis=0) # expand the 0-axis

In [ ]:
rank2Tensor

# manipulating tensors (tensor operations)
** basic operations
add, subtract, divide, multiply

there are two rules our tensor (or matrices) need to fulfil if we're going to matrix multiply them:

1. the inner demensions must match
2. resulting matrix has the same shape of the inner dimensions


In [ ]:
# you can add values to a tensor using addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor+10

In [ ]:
# original tensor unchanged
tensor

In [ ]:
# multiplication also works
tensor * 10

In [ ]:
# sub
tensor-10

In [ ]:
# we can use the tf buildin function too (Note: CODE sped up using the tensor flow functions)
tf.multiply(tensor, 10)

In [ ]:
tensor

**Matrix Multiplication**
In ML, matrix multiplication is one of the most common matrix operations.

In [ ]:
#matmul in tf
print(tensor)
tf.matmul(tensor, tensor)

In [ ]:
# matrix multiplication with python operator "@"
tensor @ tensor 


In [ ]:
tensor.shape

In [ ]:
# create a tensor (3,2) tensor 
X = tf.constant([[1,2], [3,4], [5,6]])
# create another (3, 2) tensor
Y = tf.constant([[7,8], [9,10], [11,12]])
X, Y

In [ ]:
# try to matmul tensors of the same shape
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [ ]:
# change shape of y
tf.reshape(Y, shape=(2,3))

In [ ]:
X.shape, tf.reshape(Y, shape=(2,3)).shape

In [ ]:
# try to multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

In [ ]:
tf.reshape(X, shape=(2, 3)).shape, Y.shape

In [ ]:
tf.matmul( tf.reshape(X, shape=(2,3)), Y)

In [ ]:
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

** dot product **
matrix multiplication is also reffered to as this 
- tf.matmul()
- tf.tensordot()

In [ ]:
# perform dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# perform matrix mul between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# perform matmul between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# check the values of Y, reshape Y and transposed Y 
print("Normal Y: ")
print(Y, "\n")
print("Y reshape to (2,3): ")
print(tf.reshape(Y, (2,3)), "\n")
print("Y transposed: " )
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshape to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

changing tensor data type

In [ ]:
# create a new tensor with default datatype (float3)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([10,7])
C.dtype

tf.int32

In [ ]:
# change from float 32 to float 16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# change int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>

## aggregating tensors
- aggregating tesors = condensing them from multiple vals to smaller amount of vals

In [ ]:
## getting abs values
D = tf.constant([-7, -10])

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

forms of aggregation: 
- get min
- get max 
- get mean of tensor
- get sunm of tensor 


In [ ]:
# create random tensor with vals between 0 and 100 of size 50
import numpy as np
E= tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([70, 52, 20, 16, 32, 30, 90,  6, 37, 30, 16, 92, 53, 39, 76, 64, 58,
       86,  1, 40, 19, 55, 90, 84, 23, 80, 43, 65, 84, 81, 84, 36, 37, 33,
       64, 41, 30, 89,  0, 73, 50, 97, 85, 95, 19, 61, 10, 55, 12,  4])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find min 
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# find max 
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
# find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2507>

In [ ]:
# find variance
import tensorflow_probability as tfp
tfp.stats.variance(E)


<tf.Tensor: shape=(), dtype=int64, numpy=831>

In [ ]:
# find standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.84303>

find position max and min

In [ ]:
# create new tensor for finding positional min and max 
tf.random.set_seed(42)
P = tf.random.uniform(shape=[50])
P

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find positional max 
tf.argmax(P)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value posiion
P[tf.argmax(P)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(P)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
 P[tf.argmax(P)] == tf.reduce_max(P)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# find positional minimum
tf.argmin(P)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
P[tf.argmin(P)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### squeezing a tensor ( removing all single dimensions )

In [ ]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
squeeze = tf.squeeze(G)
squeeze, squeeze.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>, TensorShape([50]))

## one-hot encoding tensors

In [ ]:
# create list of indices 
some_list = [0,1,2,3] # could be red green blue or purple 

# one hot encode list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom vals for one-hot encoding
tf.one_hot(some_list, depth=4, on_value="full", off_value="empty")

<tf.Tensor: shape=(4, 10), dtype=string, numpy=
array([[b'full', b'empty', b'empty', b'empty', b'empty', b'empty',
        b'empty', b'empty', b'empty', b'empty'],
       [b'empty', b'full', b'empty', b'empty', b'empty', b'empty',
        b'empty', b'empty', b'empty', b'empty'],
       [b'empty', b'empty', b'full', b'empty', b'empty', b'empty',
        b'empty', b'empty', b'empty', b'empty'],
       [b'empty', b'empty', b'empty', b'full', b'empty', b'empty',
        b'empty', b'empty', b'empty', b'empty']], dtype=object)>

# squaring, log, sqrt


In [ ]:
H = tf.range(1,10)
tf.square(H), H, tf.sqrt(tf.cast(H, dtype=tf.float32))


(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>)

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# tensors and numpy 


In [ ]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert our tensor back to numpy array 
np.array(J), type(np.array(J)) 

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert tensor J to a numpy array 
J.numpy(), type(J.numpy())


(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
J = tf.constant(np.array([3., 7., 10.]))
newJ = tf.constant([3., 7., 10.])
J.dtype, newJ.dtype

(tf.float64, tf.float32)